### ISSUE TITLE
framework is not defined

### ISSUE THREAD

**Issue by jesusr** [RasCarlito/generator-fountain-backbone#2]
Hi,

when I try to use the generator, it throws an error like this:

> $-> yo fountain-backbone                                                             
> ? Which module management do you want? Webpack with NPM
> ? Which JS preprocessor do you want? ES2015 today with Babel
> ? Which CSS preprocessor do you want? SASS
> ? Which Continuous Integration platform do you want? (Press <space> to select, <a> to toggle all, <i> to inverse selec
> tion)
> ? Do you want a sample app? Just a Hello World
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> ReferenceError: /usr/local/lib/node_modules/generator-fountain-gulp/generators/app/templates/conf/gulp.conf.js:14
>     12| const gutil = require('gulp-util');
>     13|
>  >> 14| <% if (framework === 'angular1') { -%>
>     15| exports.ngModule = 'app';
>     16|
>     17| <% } -%>
> 
> framework is not defined
>     at eval (eval at compile (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:12)
>     at returnedFn (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/ejs/lib/ejs.js:580:17)
>     at Object.exports.render (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/ejs/lib/ejs.js:384:37)
>     at process (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
>     at applyProcessingFunc (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
>     at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
>     at files.forEach.file (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
>     at Array.forEach (native)
>     at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
>     at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-fountain-gulp/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
>

**Comment by ghost** [comment]
Hi @jesusr , sorry for not responding earlier.

This generator was designed to work with [FountainJS/generator-fountain-webapp](https://github.com/FountainJS/generator-fountain-webapp)
The backbone generator did not become official so it is not packaged along with FountainJS

You need to install FountainJS and clone the backbone generator and run `npm link` inside the repo.

Then you should be able to run `yo fountain-webapp` and the backbone generator will appear in the list.

I am not completely sure of the steps I just explained. Maybe @zckrs can correct me if I'm wrong :)

Cheers

**Comment by ghost** [comment]
But you should really be looking into more modern frameworks like React, Vue, Choo, Angular instead of Backbone. Building modern web apps with Backbone is quite tedious nowadays compared to other frameworks on the market.

**Comment by jesusr** [comment]
@RasCarlito I was only searching for a generator for scaffolding Backbone apps because I prefer control every single component on the application, instead of heavy weight apps where I wouldnt control anything. Anyway, Backbone is a good choice if you search for a simple and lightweight app if you know how to cut off the parts you dont need.

I have other projects that needs more flexibility and my choice was usually Angular.

Thanks for your help ;)
